name: android

on:
  push:
    paths:
      - '*'
  pull_request:
    paths:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r26d
        add-to-path: false
    - name: Install dependencies
      run: |
        sudo apt install -y libc6-dev libc6-dev-i386
    - name: Build
      run: |
        echo ndk.dir = ${{ steps.setup-ndk.outputs.ndk-path }} > local.properties
        echo arch = arm64 >> local.properties
        ./Start.sh
    - name: Compress deps
      run: |
        zip -r deps_android.zip output/*
    - name: Save artifact
      uses: actions/upload-artifact@v3
      with:
        name: deps_android.zip
        path: ./deps_android.zip
